### Add a New Post
POST http://localhost:3000/post
Content-Type: application/json

{
  "title": "hello",
  "sender": "May",
  "body": "shalom!"
}

### Get All Posts
GET http://localhost:3000/posts

### Get a Post by ID
GET http://localhost:3000/post/6761c4985718dc2730580f45

### Get Posts by Sender
GET http://localhost:3000/post?sender=Avi

### Update a Post
PUT http://localhost:3000/post/1
Content-Type: application/json

{
  "description": "bye!"
}


//----------------------------------------------->

### Create a Comment (POST)
POST http://localhost:3000/comment
Content-Type: application/json

{
  "body": "bye!",
  "postId": "6761c4985718dc2730580f45"
}

### Read a Comment by id (GET)
GET http://localhost:3000/comment/

### Update a Comment (POST)
PUT http://localhost:3000/comment/1
Content-Type: application/json

{
  "message": "bye!"
}

### Delete a Comment (DELETE)
GET http://localhost:3000/comment/1

### Get All Comments
GET http://localhost:3000/comments

### Get All Comments by Post
GET http://localhost:3000/comments?postId=6761c4985718dc2730580f45


