### Register new User
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username": "mori8",
  "email": "mori8@gmail.com",
  "password": "123"
}

### Login new User
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "mori7",
  "password": "123"
}

### Logout
POST http://localhost:3000/users/logout

### Get All Users
GET http://localhost:3000/users

### Get User by ID
GET http://localhost:3000/users/67687dc20cdaa32f405eeda5

### Update User by ID
PUT http://localhost:3000/users/67687dc20cdaa32f405eeda5
Content-Type: application/json

{
  "username": "maychu1",
  "email": "maychu1@gmail.com",
  "password": "1234"
}

### Delete User by ID
DELETE http://localhost:3000/users/6768758131002c769325e699

### Create a New Post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "My New Post4",
  "body": "post!"
  }

### Get All Posts
GET http://localhost:3000/posts

### Get Post by author
GET http://localhost:3000/posts
Content-Type: application/json

{
  "sender": "67756aa95fd92b49e2da43e2"
}

### Get Post by ID
GET http://localhost:3000/posts/677573bee5ba3a5a9782fe6d

### Update Post by ID
PUT http://localhost:3000/posts/677586807fc995d5c981d6b3
Content-Type: application/json

{
  "title": "Updated Post Title",
  "body": "Updated content of the post"
}

### Delete Post by ID
DELETE http://localhost:3000/posts/677586807fc995d5c981d6b3

### Create a New Comment for a Post
POST http://localhost:3000/comments
Content-Type: application/json

{
  "body": "Cool!",
  "postId": "676882ca74db5e158e34f234",
  "userId": "6768758831002c769325e69c"
}

### Get All Comments
GET http://localhost:3000/comments

### Get All Comments for a Specific Post
GET http://localhost:3000/comments/676882ca74db5e158e34f234

### Update Comment by ID
PUT http://localhost:3000/comments/676886182c660604ee4df6d0
Content-Type: application/json

{
  "body": "Very cool!",
  "postId": "676882ca74db5e158e34f234"
}

### Delete Comment by ID
DELETE http://localhost:3000/comments
Content-Type: application/json

{
  "id": "676886182c660604ee4df6d0",
  "postId": "676882ca74db5e158e34f234"
}
